version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: policiesdb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
