spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/policiesdbt
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /documentation.html

server:
  port: 8080

fraud-api:
  url: http://localhost:8081

---

spring:
  config:
    activate:
      on-profile: test

fraud-api:
  url: http://localhost:18081
