spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/policiesdbt
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
